### ISSUE TITLE
rmf_demos build errors: internal compiler error: in lambda_expr_this_capture

### ISSUE THREAD

**Issue by simk0024** [osrf/rmf_demos#107]
The workspace couldn't be built, and following errors was encountered when setting up.

1. rosdep install <-- hopefully no impact on colcon build error below.
```
rosdep install --from-paths src --ignore-src --rosdistro eloquent -yr

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
building_map_tools: Cannot locate rosdep definition for [python3-shapely]
traffic_editor: Cannot locate rosdep definition for [libignition-common3-dev]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully
```
2. colcon build --cmake-args -DCMAKE_BUILD_TYPE=RELEASE
```
rmf_demos_ws/src/rmf/rmf_core/rmf_fleet_adapter/src/rmf_fleet_adapter/phases/../services/detail/impl_Negotiate.hpp:133:34: internal compiler error: in lambda_expr_this_capture, at cp/lambda.c:774
             [n = shared_from_this()]()

```

Thanks.

**Comment by Yadunund** [comment]
Hi,

The rosdep error is okay to ignore as those dependencies are manually installed in the Setup step https://github.com/osrf/rmf_demos#setup
The second error is related to the compiler version used. As stated in the Compiling instructions https://github.com/osrf/rmf_demos#compiling-instructions, please use GCC version 8 or above.
