### ISSUE TITLE
Improve visualization of the maps

### ISSUE THREAD

**Issue by koonpeng** [osrf/rmf_demos#149]
Moved over from https://github.com/osrf/romi-dashboard/issues/137

---

Since we agreed to have a sandbox for the tutorial, with a particular map (which could be the office map), I think it would be interesting to improve this map (make something similar to the airport maybe), because it will be displayed in all Romi-dashboard instances that future clients will have.
Current office blueprint:

![image](https://user-images.githubusercontent.com/11761240/95614844-94c2a880-0a3d-11eb-86aa-39a550a7177f.png)

Simulation map viewed from above
![office](https://user-images.githubusercontent.com/11761240/95615135-1a465880-0a3e-11eb-991e-d09dca12287e.png)

**Comment by Yadunund** [comment]
Migrated to https://github.com/open-rmf/rmf_demos/issues/56
