### ISSUE TITLE
Handshake timed out on SROS 2

### ISSUE THREAD

**Issue by marcoag** [osrf/rmf_demos#159]
After a couple minutes of running the secured office demo this message comes up on all the tmux windows

`fsm: handshake (lguid=e0e9560c:e7a9052e:270b167b:1c1 rguid=d52568ea:4d08201b:d6a90132:1c1) failed: (1) Timed out`

The simulation becomes unresponsive afterwards.

**Comment by marcoag** [comment]
Run this with the following versions:

`cyclone`: b025095161ce61dfe9ddbde7fbc13962f8051de2 from `master`
`rmw_cyclone`:  0.7.4 

Around 20 mins with non stop requests and the issue didn't show up.

**Comment by Yadunund** [comment]
Migrated to https://github.com/open-rmf/rmf_demos/issues/54
