### ISSUE TITLE
Robot gets stuck on task if dispenser is set incorrectly

### ISSUE THREAD

**Issue by Achllle** [osrf/rmf_demos#160]
New to RMF here. I ran into what seems like a bug (possibly due to user error) where the task planner will get stuck if its given an invalid task.

### Steps to Reproduce

1. launch the office demo
2. manually have the fleet execute the task in the readme (start waypoint `pantry`, end waypoint `hardware_2`) with `coke_dispenser` and `coke_ingestor`. `tinyRobot2` executes the task. 
3. Set start waypoint to `hardware_2` and end waypoint to `hardware_1` and leave the delivery variables as is.

**Expected outcome**: the robot either executes the task the best it can or the planner errors out
**Actual outcome**: the fleet manager gets stuck, continuously printing out `Remaining phases: 3`. The robot doesn't budge.

When creating the first, valid task then, the other robot executes it but gets stuck because the first robot `tinyRobot2` won't move.

**Comment by Yadunund** [comment]
Hi @Achllle ,

Glad to hear that you're trying out the `rmf_demos`!

This is a known usability shortcoming of the `RMF Panel` which is used to send task requests to RMF. There is an implicit binding of waypoint names and dispensers/ingestors names at waypoints. The `office` world currently only has [one](https://github.com/osrf/rmf_demos/blob/599ae8b7949de467b4c1afbbfaf50db870417686/rmf_demo_maps/maps/office/office.building.yaml#L112) `dispenser` named `coke_dispenser` located at the `pantry` waypoint and [one](https://github.com/osrf/rmf_demos/blob/599ae8b7949de467b4c1afbbfaf50db870417686/rmf_demo_maps/maps/office/office.building.yaml#L114) `ingestor` named `coke_ingestor` located at `hardware_2`.  As a result only one kind of delivery can be performed: from the `pantry` to `hardware_2`.  If any other combination of waypoint names and dispenser/ingestor names is inputted, the task will not succeed and may result in a permanent state of execution as the robot waits to receive a response from a dispenser/ingestor which does not exist at that location. 

To alleviate this problem, we are currently in the process of revamping the UI to only allow the user to submit valid delivery requests. 

In your case if you wish to also perform deliveries between `hardware_2` and `hardware_1`, you may place a `TeleportDispenser` model at `hardware_2` and another `TeleportIngestor` model at `hardware_1` with unique names each. You will also need to place a non-static object that is to be delivered at `hardware_2`. 

Let us know if you have any other questions in the meanwhile.

**Comment by Achllle** [comment]
Thanks for the elaborate explanation. Regardless of the implementation on the frontend, wouldn't the correct behavior for the planner be to fail and move to the next task?

**Comment by aaronchongth** [comment]
Hello @Achllle!

You are absolutely right, that would be the appropriate behaviour. However as @Yadunund mentioned, the RMF Panel is currently in the process of being deprecated, and at the same time the messaging interface that the panel has been using all this time has been migrated to be an implementation interface and should no longer be used by frontend applications.

The current example fleet adapter implementation assumes deliveries can be performed regardless of the context, as seen here https://github.com/osrf/rmf_core/blob/b864d20d615f31febf30e77ab27f4596cad28e36/rmf_fleet_adapter/src/full_control/main.cpp#L385-L391

We will be rolling out the next iteration's task dispatching system soon, with it's accompanying UI, which will behave as you mentioned, and fail the task planning without assigning it to any one robot.

Do let us know if you have any lingering questions!

**Comment by tanyouliang95** [comment]
rviz task panel is no longer in used. Use `ros2 run rmf_demos_tasks dispatch_delivery` CLI, `rmf_demos_panel`, or `rmf-web` to dispatch a delivery task.
