### ISSUE TITLE
How to publish robot's current floor name in the level name field of its RobotState?

### ISSUE THREAD

**Issue by Marcusttk** [osrf/rmf_demos#183]
I have built my own world environment, rviz panel, gazebo works fine.

However the robot cant be spawned.

The navigation file path is found, the waypoints are added. However I get the following error message.
![image](https://user-images.githubusercontent.com/34367656/104685257-90411680-5735-11eb-9899-cfe675fb2633.png)

Please advise.

**Comment by Yadunund** [comment]
Hi,

When reporting an issue, kindly provide basic information including the OS version, branch names of the various RMF packages in your workspace and the commands used to launch your world.

Having said that, in your case it looks like a process (`building_map_server`) has crashed on launch. Could you copy-paste the entire terminal output here?

**Comment by Marcusttk** [comment]
> Hi,
> 
> When reporting an issue, kindly provide basic information including the OS version, branch names of the various RMF packages in your workspace and the commands used to launch your world.
> 
> Having said that, in your case it looks like a process (`building_map_server`) has crashed on launch. Could you copy-paste the entire terminal output here?

OS version: 20.04, ros foxy 
Branch: Master of rmf demos

commands used: ros2 launch demos imda.launch.xml

terminal output:

marcus@hp:~$ source ~/rmf_demos_ws/install/setup.bash
marcus@hp:~$ ros2 launch demos imda.launch.xml
[INFO] [launch]: All log files can be found below /home/marcus/.ros/log/2021-01-15-10-27-25-297489-hp-2601
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rmf_traffic_schedule-1]: process started with pid [2603]
[INFO] [rmf_traffic_blockade-2]: process started with pid [2605]
[INFO] [building_map_server-3]: process started with pid [2607]
[INFO] [rviz2-4]: process started with pid [2609]
[INFO] [fleet_state_visualizer-5]: process started with pid [2611]
[INFO] [building_systems_visualizer-6]: process started with pid [2613]
[INFO] [rviz2-7]: process started with pid [2615]
[INFO] [door_supervisor-8]: process started with pid [2617]
[INFO] [lift_supervisor-9]: process started with pid [2619]
[INFO] [gzserver-10]: process started with pid [2621]
[INFO] [gzclient-11]: process started with pid [2623]
[INFO] [full_control-12]: process started with pid [2625]
[INFO] [robot_state_aggregator-13]: process started with pid [2627]
[rmf_traffic_blockade-2] [INFO] [1610677645.611318307] [rmf_traffic_blockade_node]: Beginning traffic blockade node
[full_control-12] [INFO] [1610677645.614957622] [tinyRobot_fleet_adapter]: Parameter [discovery_timeout] set to: 60.000000
[rmf_traffic_schedule-1] [INFO] [1610677645.618636733] [rmf_traffic_schedule_node]: Beginning traffic schedule node
[rmf_traffic_schedule-1] [INFO] [1610677645.624141219] [rmf_traffic_schedule_node]: [1] Registered query
[full_control-12] [INFO] [1610677645.634992282] [tinyRobot_fleet_adapter]: Parameter [linear_velocity] set to: 0.500000
[full_control-12] [INFO] [1610677645.635108364] [tinyRobot_fleet_adapter]: Parameter [angular_velocity] set to: 0.600000
[full_control-12] [INFO] [1610677645.635201427] [tinyRobot_fleet_adapter]: Parameter [linear_acceleration] set to: 0.750000
[full_control-12] [INFO] [1610677645.635286197] [tinyRobot_fleet_adapter]: Parameter [angular_acceleration] set to: 2.000000
[full_control-12] [INFO] [1610677645.635362101] [tinyRobot_fleet_adapter]: Parameter [footprint_radius] set to: 0.300000
[full_control-12] [INFO] [1610677645.635432209] [tinyRobot_fleet_adapter]: Parameter [vicinity_radius] set to: 1.500000
[full_control-12] [INFO] [1610677645.635500330] [tinyRobot_fleet_adapter]: Parameter [reversible] set to: 1
[full_control-12] The fleet [tinyRobot] has the following named waypoints:
[full_control-12]  -- lift_lobby
[full_control-12]  -- 12
[full_control-12]  -- 11
[full_control-12]  -- exit_lift
[full_control-12]  -- 5
[full_control-12]  -- 3
[full_control-12]  -- 4
[full_control-12]  -- 14
[full_control-12]  -- 6
[full_control-12]  -- 1
[full_control-12]  -- tinyRobot2_charger
[full_control-12]  -- 9
[full_control-12]  -- enter_lift
[full_control-12]  -- 15
[full_control-12]  -- 2
[full_control-12]  -- 7
[full_control-12]  -- 8
[full_control-12] [INFO] [1610677645.639051939] [tinyRobot_fleet_adapter]: Parameter [delay_threshold] set to: 15.000000
[full_control-12] [INFO] [1610677645.641077130] [tinyRobot_fleet_adapter]: Starting Fleet Adapter
[rmf_traffic_schedule-1] [INFO] [1610677645.861383676] [rmf_traffic_schedule_node]: [2] Registered query
[rviz2-4] [INFO] [1610677645.874506669] [viz]: VisualizerDataNode /viz started...
[gzclient-11] Gazebo multi-robot simulator, version 11.3.0
[gzclient-11] Copyright (C) 2012 Open Source Robotics Foundation.
[gzclient-11] Released under the Apache 2 License.
[gzclient-11] http://gazebosim.org
[gzclient-11] 
[gzserver-10] Gazebo multi-robot simulator, version 11.3.0
[gzserver-10] Copyright (C) 2012 Open Source Robotics Foundation.
[gzserver-10] Released under the Apache 2 License.
[gzserver-10] http://gazebosim.org
[gzserver-10] 
[rviz2-7] [INFO] [1610677646.148779849] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-7] [INFO] [1610677646.148935820] [rviz2]: OpenGl version: 4.3 (GLSL 4.3)
[rviz2-7] [INFO] [1610677646.190915604] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-4] [INFO] [1610677646.519207645] [rviz_node]: Rviz parameters updated
[fleet_state_visualizer-5] [INFO] [1610677646.522919317] [fleet_state_visualizer]: hello i am fleet state visualizer
[building_systems_visualizer-6] [INFO] [1610677646.776867417] [building_systems_visualizer]: Building systems visualizer started...
[building_map_server-3] [INFO] [1610677646.796187001] [building_map_server]: loading map path: /home/marcus/rmf_demos_ws/install/rmf_demo_maps/share/rmf_demo_maps/imda/imda.building.yaml
[gzserver-10] [INFO] [1610677647.055437788] [slotcar_tinyRobot2]: Setting nominal drive speed to: 0.500000
[gzserver-10] [INFO] [1610677647.055846090] [slotcar_tinyRobot2]: Setting nominal drive acceleration to: 0.250000
[gzserver-10] [INFO] [1610677647.055866144] [slotcar_tinyRobot2]: Setting max drive acceleration to: 0.750000
[gzserver-10] [INFO] [1610677647.055876122] [slotcar_tinyRobot2]: Setting nominal turn speed to:0.600000
[gzserver-10] [INFO] [1610677647.055885281] [slotcar_tinyRobot2]: Setting nominal turn acceleration to:1.500000
[gzserver-10] [INFO] [1610677647.055893892] [slotcar_tinyRobot2]: Setting max turn acceleration to:2.000000
[gzserver-10] [INFO] [1610677647.055902473] [slotcar_tinyRobot2]: Setting stop distance to:0.750000
[gzserver-10] [INFO] [1610677647.055911004] [slotcar_tinyRobot2]: Setting stop radius to:0.750000
[gzserver-10] [INFO] [1610677647.055919963] [slotcar_tinyRobot2]: Setting tire radius to:0.100000
[gzserver-10] [INFO] [1610677647.055928432] [slotcar_tinyRobot2]: Setting base width to: 0.320600
[gzserver-10] [INFO] [1610677647.055936185] [slotcar_tinyRobot2]: Setting nominal voltage to: 12.000000
[gzserver-10] [INFO] [1610677647.055942953] [slotcar_tinyRobot2]: Setting nominal capacity to: 24.000000
[gzserver-10] [INFO] [1610677647.055949322] [slotcar_tinyRobot2]: Setting charging current to: 2.000000
[gzserver-10] [INFO] [1610677647.055955693] [slotcar_tinyRobot2]: Setting mass to: 20.000000
[gzserver-10] [INFO] [1610677647.055962193] [slotcar_tinyRobot2]: Setting inertia to: 10.000000
[gzserver-10] [INFO] [1610677647.055968559] [slotcar_tinyRobot2]: Setting friction coefficient to: 0.300000
[gzserver-10] [INFO] [1610677647.055974791] [slotcar_tinyRobot2]: Setting nominal power to: 10.000000
[gzserver-10] [INFO] [1610677647.055986872] [slotcar_tinyRobot2]: Setting name to: tinyRobot2
[gzserver-10] [INFO] [1610677647.075901522] [slotcar_tinyRobot2]: Initialising slotcar for tinyRobot2
[gzserver-10] [INFO] [1610677647.105274160] [door]: Loading DoorPlugin for [Cargo_lift_door]
[gzserver-10] [Msg] Waiting for master.
[gzserver-10] [Msg] Connected to gazebo master @ http://127.0.0.1:11345
[gzserver-10] [Msg] Publicized address: 192.168.50.228
[gzserver-10] [Msg] Loading world file [/home/marcus/rmf_demos_ws/install/rmf_demo_maps/share/rmf_demo_maps/maps/imda_world/imda.world]
[gzserver-10] Using specified value [0.5] for property [v_max_door]
[gzserver-10] Using specified value [0.3] for property [a_max_door]
[gzserver-10] Using specified value [0.15] for property [a_nom_door]
[gzserver-10] Using specified value [0.01] for property [dx_min_door]
[gzserver-10] Using specified value [500] for property [f_max_door]
[gzserver-10] Using specified attribute value [empty_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [right_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [SwingDoor] for property [type]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [1.57] for property [upper]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [1.57] for property [upper]
[gzserver-10] [INFO] [1610677647.111080342] [door]: Finished loading [Cargo_lift_door]
[gzserver-10] [WARN] [1610677647.111296312] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[gzserver-10] [INFO] [1610677647.120467305] [door]: Loading DoorPlugin for [lift_door_1]
[gzserver-10] Using specified value [0.5] for property [v_max_door]
[gzserver-10] Using specified value [0.3] for property [a_max_door]
[gzserver-10] Using specified value [0.15] for property [a_nom_door]
[gzserver-10] Using specified value [0.01] for property [dx_min_door]
[gzserver-10] Using specified value [500] for property [f_max_door]
[gzserver-10] Using specified attribute value [empty_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [right_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [SwingDoor] for property [type]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [1.57] for property [upper]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [1.57] for property [upper]
[gzserver-10] [INFO] [1610677647.125765868] [door]: Finished loading [lift_door_1]
[gzserver-10] [WARN] [1610677647.126063475] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[gzserver-10] [INFO] [1610677647.134629848] [door]: Loading DoorPlugin for [lift_door_2]
[gzserver-10] Using specified value [0.5] for property [v_max_door]
[gzserver-10] Using specified value [0.3] for property [a_max_door]
[gzserver-10] Using specified value [0.15] for property [a_nom_door]
[gzserver-10] Using specified value [0.01] for property [dx_min_door]
[gzserver-10] Using specified value [500] for property [f_max_door]
[gzserver-10] Using specified attribute value [empty_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [right_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [SwingDoor] for property [type]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [1.57] for property [upper]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [1.57] for property [upper]
[gzserver-10] [INFO] [1610677647.139641741] [door]: Finished loading [lift_door_2]
[gzserver-10] [WARN] [1610677647.139885978] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[gzserver-10] [INFO] [1610677647.151255158] [door]: Loading DoorPlugin for [lift_door_3]
[gzserver-10] Using specified value [0.5] for property [v_max_door]
[gzserver-10] Using specified value [0.3] for property [a_max_door]
[gzserver-10] Using specified value [0.15] for property [a_nom_door]
[gzserver-10] Using specified value [0.01] for property [dx_min_door]
[gzserver-10] Using specified value [500] for property [f_max_door]
[gzserver-10] Using specified attribute value [empty_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [right_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [SwingDoor] for property [type]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [1.57] for property [upper]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [1.57] for property [upper]
[gzserver-10] [INFO] [1610677647.156829928] [door]: Finished loading [lift_door_3]
[gzserver-10] [WARN] [1610677647.157090954] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[gzserver-10] [INFO] [1610677647.166015357] [door]: Loading DoorPlugin for [lift_door_6]
[gzserver-10] Using specified value [0.5] for property [v_max_door]
[gzserver-10] Using specified value [0.3] for property [a_max_door]
[gzserver-10] Using specified value [0.15] for property [a_nom_door]
[gzserver-10] Using specified value [0.01] for property [dx_min_door]
[gzserver-10] Using specified value [500] for property [f_max_door]
[gzserver-10] Using specified attribute value [left_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [empty_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [SwingDoor] for property [type]
[gzserver-10] Using specified attribute value [left_joint] for property [name]
[gzserver-10] Using specified value [-1.57] for property [lower]
[gzserver-10] Using specified value [0] for property [upper]
[gzserver-10] Using specified attribute value [left_joint] for property [name]
[gzserver-10] Using specified value [-1.57] for property [lower]
[gzserver-10] Using specified value [0] for property [upper]
[gzserver-10] [INFO] [1610677647.175446786] [door]: Finished loading [lift_door_6]
[gzserver-10] [WARN] [1610677647.175979493] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[building_map_server-3] Traceback (most recent call last):
[building_map_server-3]   File "/home/marcus/rmf_demos_ws/install/building_map_tools/lib/building_map_tools/building_map_server", line 11, in <module>
[building_map_server-3]     load_entry_point('building-map-tools==0.0.0', 'console_scripts', 'building_map_server')()
[building_map_server-3]   File "/home/marcus/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map_server/building_map_server.py", line 206, in main
[building_map_server-3]     n = BuildingMapServer(map_path)
[building_map_server-3]   File "/home/marcus/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map_server/building_map_server.py", line 46, in __init__
[building_map_server-3]     self.map_msg = self.building_map_msg(self.building)
[building_map_server-3]   File "/home/marcus/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map_server/building_map_server.py", line 71, in building_map_msg
[building_map_server-3]     msg.levels.append(self.level_msg(level_data))
[building_map_server-3]   File "/home/marcus/rmf_demos_ws/install/building_map_tools/lib/python3.8/site-packages/building_map_server/building_map_server.py", line 135, in level_msg
[building_map_server-3]     gn.name = v[2]['name']
[building_map_server-3]   File "/home/marcus/rmf_demos_ws/install/building_map_msgs/lib/python3.8/site-packages/building_map_msgs/msg/_graph_node.py", line 167, in name
[building_map_server-3]     assert \
[building_map_server-3] AssertionError: The 'name' field must be of type 'str'
[gzserver-10] [INFO] [1610677647.188789468] [door]: Loading DoorPlugin for [lift_door_5]
[gzserver-10] Using specified value [0.5] for property [v_max_door]
[gzserver-10] Using specified value [0.3] for property [a_max_door]
[gzserver-10] Using specified value [0.15] for property [a_nom_door]
[gzserver-10] Using specified value [0.01] for property [dx_min_door]
[gzserver-10] Using specified value [500] for property [f_max_door]
[gzserver-10] Using specified attribute value [left_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [empty_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [SwingDoor] for property [type]
[gzserver-10] Using specified attribute value [left_joint] for property [name]
[gzserver-10] Using specified value [-1.57] for property [lower]
[gzserver-10] Using specified value [0] for property [upper]
[gzserver-10] Using specified attribute value [left_joint] for property [name]
[gzserver-10] Using specified value [-1.57] for property [lower]
[gzserver-10] Using specified value [0] for property [upper]
[gzserver-10] [INFO] [1610677647.195628741] [door]: Finished loading [lift_door_5]
[gzserver-10] [WARN] [1610677647.195976671] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[gzserver-10] [INFO] [1610677647.207358466] [door]: Loading DoorPlugin for [lift_door_4]
[gzserver-10] Using specified value [0.5] for property [v_max_door]
[gzserver-10] Using specified value [0.3] for property [a_max_door]
[gzserver-10] Using specified value [0.15] for property [a_nom_door]
[gzserver-10] Using specified value [0.01] for property [dx_min_door]
[gzserver-10] Using specified value [500] for property [f_max_door]
[gzserver-10] Using specified attribute value [left_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [empty_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [SwingDoor] for property [type]
[gzserver-10] Using specified attribute value [left_joint] for property [name]
[gzserver-10] Using specified value [-1.57] for property [lower]
[gzserver-10] Using specified value [0] for property [upper]
[gzserver-10] Using specified attribute value [left_joint] for property [name]
[gzserver-10] Using specified value [-1.57] for property [lower]
[gzserver-10] Using specified value [0] for property [upper]
[gzserver-10] [INFO] [1610677647.215892814] [door]: Finished loading [lift_door_4]
[gzserver-10] [WARN] [1610677647.216242705] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[gzserver-10] [INFO] [1610677647.226037079] [door]: Loading DoorPlugin for [ShaftDoor_Lift1_L6_lift_door]
[gzserver-10] Using specified value [0.3] for property [v_max_door]
[gzserver-10] Using specified value [0.2] for property [a_max_door]
[gzserver-10] Using specified value [0.1] for property [a_nom_door]
[gzserver-10] Using specified value [0.0001] for property [dx_min_door]
[gzserver-10] Using specified value [35] for property [f_max_door]
[gzserver-10] Using specified attribute value [left_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [right_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [DoubleSlidingDoor] for property [type]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [0.5] for property [upper]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [0.5] for property [upper]
[gzserver-10] Using specified attribute value [left_joint] for property [name]
[gzserver-10] Using specified value [-0.5] for property [lower]
[gzserver-10] Using specified value [0] for property [upper]
[gzserver-10] Using specified attribute value [ramp_joint] for property [name]
[gzserver-10] [INFO] [1610677647.233926577] [door]: Finished loading [ShaftDoor_Lift1_L6_lift_door]
[gzserver-10] [WARN] [1610677647.234256122] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[gzserver-10] [INFO] [1610677647.245361252] [door]: Loading DoorPlugin for [ShaftDoor_Lift1_L7_lift_door]
[gzserver-10] Using specified value [0.3] for property [v_max_door]
[gzserver-10] Using specified value [0.2] for property [a_max_door]
[gzserver-10] Using specified value [0.1] for property [a_nom_door]
[gzserver-10] Using specified value [0.0001] for property [dx_min_door]
[gzserver-10] Using specified value [35] for property [f_max_door]
[gzserver-10] Using specified attribute value [left_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [right_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [DoubleSlidingDoor] for property [type]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [0.5] for property [upper]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [0.5] for property [upper]
[gzserver-10] Using specified attribute value [left_joint] for property [name]
[gzserver-10] Using specified value [-0.5] for property [lower]
[gzserver-10] Using specified value [0] for property [upper]
[gzserver-10] Using specified attribute value [ramp_joint] for property [name]
[gzserver-10] [INFO] [1610677647.255045911] [door]: Finished loading [ShaftDoor_Lift1_L7_lift_door]
[ERROR] [building_map_server-3]: process has died [pid 2607, exit code 1, cmd '/home/marcus/rmf_demos_ws/install/building_map_tools/lib/building_map_tools/building_map_server /home/marcus/rmf_demos_ws/install/rmf_demo_maps/share/rmf_demo_maps/imda/imda.building.yaml --ros-args'].
[gzserver-10] [INFO] [1610677647.288554575] [lift]: Loading LiftPlugin for [Lift1]
[gzserver-10] Using specified value [2] for property [v_max_cabin]
[gzserver-10] Using specified value [1.2] for property [a_max_cabin]
[gzserver-10] Using specified value [1] for property [a_nom_cabin]
[gzserver-10] Using specified value [0.001] for property [dx_min_cabin]
[gzserver-10] Using specified value [25323] for property [f_max_cabin]
[gzserver-10] Using specified value [cabin_joint] for property [cabin_joint_name]
[gzserver-10] Using specified attribute value [L6] for property [name]
[gzserver-10] Using specified attribute value [-20] for property [elevation]
[gzserver-10] Using specified attribute value [CabinDoor_Lift1_lift_door] for property [cabin_door]
[gzserver-10] Using specified attribute value [ShaftDoor_Lift1_L6_lift_door] for property [shaft_door]
[gzserver-10] Using specified attribute value [L7] for property [name]
[gzserver-10] Using specified attribute value [0] for property [elevation]
[gzserver-10] Using specified attribute value [CabinDoor_Lift1_lift_door] for property [cabin_door]
[gzserver-10] Using specified attribute value [ShaftDoor_Lift1_L7_lift_door] for property [shaft_door]
[gzserver-10] Using specified value [L6] for property [initial_floor]
[gzserver-10] Loaded lift: Lift1
[gzserver-10] Names  |  Elevations
[gzserver-10] L7  |  0
[gzserver-10] L6  |  -20
[gzserver-10] [INFO] [1610677647.294367184] [lift]: Finished loading [Lift1]
[gzserver-10] [WARN] [1610677647.294589433] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[gzserver-10] [INFO] [1610677647.306105802] [door]: Loading DoorPlugin for [CabinDoor_Lift1_lift_door]
[gzserver-10] Using specified value [0.3] for property [v_max_door]
[gzserver-10] Using specified value [0.2] for property [a_max_door]
[gzserver-10] Using specified value [0.1] for property [a_nom_door]
[gzserver-10] Using specified value [0.0001] for property [dx_min_door]
[gzserver-10] Using specified value [35] for property [f_max_door]
[gzserver-10] Using specified attribute value [left_joint] for property [left_joint_name]
[gzserver-10] Using specified attribute value [right_joint] for property [right_joint_name]
[gzserver-10] Using specified attribute value [DoubleSlidingDoor] for property [type]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [0.5] for property [upper]
[gzserver-10] Using specified attribute value [right_joint] for property [name]
[gzserver-10] Using specified value [0] for property [lower]
[gzserver-10] Using specified value [0.5] for property [upper]
[gzserver-10] Using specified attribute value [left_joint] for property [name]
[gzserver-10] Using specified value [-0.5] for property [lower]
[gzserver-10] Using specified value [0] for property [upper]
[gzserver-10] [INFO] [1610677647.316474356] [door]: Finished loading [CabinDoor_Lift1_lift_door]
[rviz2-7] [INFO] [1610677647.829294312] [rmf_panel]: Loading tinyRobot..
[rmf_traffic_schedule-1] [INFO] [1610677647.829808176] [rmf_traffic_schedule_node]: Registered participant [0] named [tinyRobot2] owned by [tinyRobot]
[full_control-12] [INFO] [1610677647.830707833] [tinyRobot_fleet_adapter]: Added a robot named [tinyRobot2] with participant ID [0]
[rviz2-7] Nav File Path Found: /home/marcus/rmf_demos_ws/install/rmf_demo_maps/share/rmf_demo_maps/maps/imda_world/nav_graphs/0.yaml
[rviz2-7] Adding waypoint [1] as a parking spot
[rviz2-7] Adding waypoint [3] as a parking spot
[rviz2-7] Adding waypoint [16] as a parking spot
[rviz2-7] Adding waypoint [17] as a parking spot
[rviz2-7] Named waypoints:
[rviz2-7]  -- [lift_lobby]
[rviz2-7]  -- [12]
[rviz2-7]  -- [11]
[rviz2-7]  -- [exit_lift]
[rviz2-7]  -- [5]
[rviz2-7]  -- [3]
[rviz2-7]  -- [4]
[rviz2-7]  -- [14]
[rviz2-7]  -- [6]
[rviz2-7]  -- [1]
[rviz2-7]  -- [tinyRobot2_charger]
[rviz2-7]  -- [9]
[rviz2-7]  -- [enter_lift]
[rviz2-7]  -- [15]
[rviz2-7]  -- [2]
[rviz2-7]  -- [7]
[rviz2-7]  -- [8]
[rviz2-7] [INFO] [1610677647.863111655] [rmf_panel]: New Fleet found, refreshing...
[full_control-12] [ERROR] [1610677648.330803689] [tinyRobot_fleet_adapter]: Robot named [tinyRobot2] belonging to fleet [tinyRobot] is lost because we cannot figure out what floor it is on. Please publish the robot's current floor name in the level_name field of its RobotState.
[gzclient-11] [INFO] [1610677648.536276686] [gazebo_ros_node]: ROS was initialized without arguments.
[rviz2-7] [INFO] [1610677648.640713917] [lift_panel_session_node]: New lift [Lift1] found, refreshing...
[full_control-12] [ERROR] [1610677648.834471256] [tinyRobot_fleet_adapter]: Robot named [tinyRobot2] belonging to fleet [tinyRobot] is lost because we cannot figure out what floor it is on. Please publish the robot's current floor name in the level_name field of its RobotState.
[full_control-12] [ERROR] [1610677649.337084918] [tinyRobot_fleet_adapter]: Robot named [tinyRobot2] belonging to fleet [tinyRobot] is lost because we cannot figure out what floor it is on. Please publish the robot's current floor name in the level_name field of its RobotState.

**Comment by Yadunund** [comment]
Looks like your `building_map_server` is crashing. As a result, the building information is not available to the `slotcar` plugin which using the same to initialize the level the robot is located on. 

I suspect the crash is happening due to the naming of your level in `traffic_editor` with numericals only. Eg "1" instead of "L1". Could you share your `.building.yaml` file? If that is not permitted, could you share more on the names assigned to levels in `traffic_editor`?

**Comment by Marcusttk** [comment]
> Looks like your `building_map_server` is crashing. As a result, the building information is not available to the `slotcar` plugin which using the same to initialize the level the robot is located on.
> 
> I suspect the crash is happening due to the naming of your level in `traffic_editor` with numericals only. Eg "1" instead of "L1". Could you share your `.building.yaml` file? If that is not permitted, could you share more on the names assigned to levels in `traffic_editor`?

My levels were named L6 and L7. 

![Screenshot from 2021-01-15 17-46-37](https://user-images.githubusercontent.com/34367656/104709268-ac56af00-5759-11eb-9745-1a22c0450c72.png)

**Comment by Yadunund** [comment]
Ah just noticed this 
> [building_map_server-3] File "/home/marcus/rmf_demos_ws/install/building_map_msgs/lib/python3.8/site-packages/building_map_msgs/msg/_graph_node.py", line 167, in name

Same problem with numeric names but this time for waypoints not level names. Could you ensure none of your waypoints are named as numbers alone?

**Comment by Marcusttk** [comment]
> Ah just noticed this
> 
> > [building_map_server-3] File "/home/marcus/rmf_demos_ws/install/building_map_msgs/lib/python3.8/site-packages/building_map_msgs/msg/_graph_node.py", line 167, in name
> 
> Same problem with numeric names but this time for waypoints not level names. Could you ensure none of your waypoints are named as numbers alone?

Thanks. This fixes the problem! Really appreciate the help
