### ISSUE TITLE
Error while running office_traffic_light_test.launch.xml

### ISSUE THREAD

**Issue by RachiketArya** [osrf/rmf_demos#190]
Launching ```office_traffic_light_test.launch.xml``` throws the following error:
```
[ros2-2] ModuleNotFoundError: No module named 'rmf_demo_tasks.request_loop'
```
The cause for this error was found out to be missing ```request_loop.py``` file in ```rmf_demos_ws/src/rmf/rmf_demos/rmf_demo_tasks/rmf_demo_tasks```. This file seems to have been deleted in [fe3c82b](https://github.com/osrf/rmf_demos/commit/fe3c82b36c46065e5e3508e0c110b06021261e88#diff-8e9c28a2ad80c3c156f396b808f4cd5fc7a1773f1b5c49df6aa95d71a53fc246).

**Comment by Yadunund** [comment]
Thanks for reporting this issue. I have opened a [PR](https://github.com/osrf/rmf_demos/pull/195) to re-introduce the `request_loop` task solely for the purpose of simulating `mock_traffic_light` fleets.

Do note that the `full_control` fleets will not respond to this request. Instead, you should use the `rmf_demo_panel` to send task requests for these fleets.

**Comment by RachiketArya** [comment]
Thank you for the instructions @Yadunund

**Comment by Yadunund** [comment]
@RachiketArya the script should available now. Please re-open this ticket if any issue persists.
