### ISSUE TITLE
Is it required to customized your own RViz?

### ISSUE THREAD

**Issue by destkk** [osrf/rmf_demos#193]
Hi there. Can I check if I were to create a new map using traffic editor, do I need to also create a RViz file or I could just take any of the sample files from the demos folder (e.g. hotel.rviz) and rename it?

**Comment by tanyouliang95** [comment]
@destkk You can rename the same `.rviz` file. The purpose of the `.rviz` file is purely to configure rviz, which is used to visualize topics.

**Comment by Yadunund** [comment]
@destkk please open an `Issue` to report bugs only. For general questions or technical help, please use the `Discussions` tab.
