### ISSUE TITLE
How to send loop request via RMF Panel in RViz

### ISSUE THREAD

**Issue by destkk** [osrf/rmf_demos#196]
Hi there. May I know is it possible to send a loop request via RMF Panel in RViz or Configure the GUI for localhost RMF Panel? I have tested and it did send a loop request but the robot does not move.
Using Ubuntu 20.04
![Screenshot from 2021-01-22 12-29-55](https://user-images.githubusercontent.com/63645940/105446795-d48c6380-5cad-11eb-967d-2b8bb137e8d1.png)
![Screenshot from 2021-01-22 12-36-26](https://user-images.githubusercontent.com/63645940/105447113-89bf1b80-5cae-11eb-8cf4-8bb096245784.png)

**Comment by Yadunund** [comment]
@destkk,

As mentioned before, please use the Q&A in the `Discussions` tab to ask for technical help next time.

To answer your question, can you provide these details:

**Workspace information:**
 - Operating system and version:
 - ROS distribution:
 - ROS installation method: [from binary packages or from source]
 - RMF installation method: [from binary packages or from source]
 - RMF binaries version, if installed from binaries:
 - RMF source versions, if installed from source:
   - `rmf_demos` branch or commit hash: 
   - `rmf_core` branch or commit hash: 
   - `rmf_schedule_visualizaer` branch or commit hash: 
   - `traffic_editor` branch or commit hash:

**Comment by tanyouliang95** [comment]
Something to add on. With the new dispatching system: https://github.com/osrf/rmf_core/pull/217, the previous `/loop_requests` and `/delivery_requests` topics are no longer available. Thus, the rviz `rmf_panel` for task request is deprecated. The current recommended way to dispatch task is to use the web-based `rmf_demos_panel`.

On the side note, user can bypass the gui, and directly submit a task via the below ros srv call to `dispatcher_node`. Example:
```bash
ros2 service call /submit_task rmf_task_msgs/srv/SubmitTask '{description: {task_type:{type: 1}, loop: {start_name: 'cubicle_1', finish_name: 'lounge', num_loops: 2}}}'
```

Still, it is recommended to use the web gui to initiate task. To have your own customized dropdown in `rmf_demo_panel`, you can edit the `/rmf_dashbord_resources/$WORLD/dashboard_config.json` and then recompile.

**Comment by destkk** [comment]
> Something to add on. With the new dispatching system: [osrf/rmf_core#217](https://github.com/osrf/rmf_core/pull/217), the previous `/loop_requests` and `/delivery_requests` topics are no longer available. Thus, the rviz `rmf_panel` for task request is deprecated. The current recommended way to dispatch task is to use the web-based `rmf_demos_panel`.
> 
> On the side note, user can bypass the gui, and directly submit a task via the below ros srv call to `dispatcher_node`. Example:
> 
> ```shell
> ros2 service call /submit_task rmf_task_msgs/srv/SubmitTask '{description: {task_type:{type: 1}, loop: {start_name: 'cubicle_1', finish_name: 'lounge', num_loops: 2}}}'
> ```
> 
> Still, it is recommended to use the web gui to initiate task. To have your own customized dropdown in `rmf_demo_panel`, you can edit the `/rmf_dashbord_resources/$WORLD/dashboard_config.json` and then recompile.

Thanks for the advice. May I know how do I recompile them?

**Comment by tanyouliang95** [comment]
Hi sorry for the late reply. To recompile the panel, you will need to go through the same steps of `npm run build `. On the side note, to ease the testing without using the web gui, you can also use the `dispatch_loop` scripts via CLI. https://github.com/osrf/rmf_demos/pull/199

Example:
```bash
ros2 run rmf_demo_tasks dispatch_loop -s coe -f lounge -n 3 --use_sim_time
```
