### ISSUE TITLE
Protobuf incompatibility errors

### ISSUE THREAD

**Issue by cnboonhan94** [osrf/rmf_demos#21]
I am encountering challenging errors regarding protobuf incompatibility on my laptop. ( Apex 15 Aftershock ).  

Thus during build, I encounter a build warning 
`Protobuf compiler version does 3.4.0 does not match library version 3.0.0`. 
Additionally, during running of the demo I get errors as well:
`
[gzserver-7] [libprotobuf FATAL google/protobuf/stubs/common.cc:67] This program requires version 3.4.0 of the Protocol Buffer runtime library, but the installed version is 3.0.0.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/home/bhan/dev/cartographer_ws/protobuf/src/google/protobuf/descriptor.pb.cc".)
`

the output of `/usr/bin/protoc --version` is `3.0.0` while `/lusr/local/bin/protoc --version` is `3.4.0`.  It seems that somehow the build process "finds" the old version first.

What might be the best way to avoid this?

**Comment by cnboonhan94** [comment]
To add on, i think this is more of a gazebo issue rather than a rmf_demos issue.

**Comment by Yadunund** [comment]
Yes, this is related to conflicting version of protobuf on your machine. Seems like google-cartographer requires the install of a newer version of protobuf as reported in a similar issue [here](https://bitbucket.org/osrf/gazebo/issues/2496/protobuf-error-on-ubuntu-1804). Could you try uninstalling/purging the newer version?

**Comment by cnboonhan94** [comment]
What might be the best way to do so? I have tried "sudo apt remove libprotoc-dev" however this also removes ros-eloquent-gazebo-* packages. Also, I think that command removes the older "3.0" versions.

I could try sudo rm-ing the newer version in /use/local/bin and see how that goes.

**Comment by cnboonhan94** [comment]
Good news! `sudo rm /usr/local/bin/protoc` seems to fix this issue. However, i can do this only because I have no dependencies on the alternate protobuf 3.4. Perhaps there is a way to ensure that the correct version is found?

Thank you, closing for now.
