### ISSUE TITLE
Cleaning Task in airport_terminal and clinic demos not working

### ISSUE THREAD

**Issue by KamalanathanN** [osrf/rmf_demos#216]
Hi,
#### How do i configure exisiting fleets to accept cleaning tasks? and where are the zones defined inside the worlds?

**Workspace information:**
 - Operating system and version: Ubuntu 20.04
 - ROS distribution: ROS2 Foxy
 - ROS installation method: from binary packages
 - RMF installation method: from source

**Steps to Reproduce**
1. Inside RMF Panel 
2. Task type Clean
3. zone_1

**Expected behavior**
I guess its supposed to do some kind of coverage planning inside defined zones.
**Actual behavior**
On submitting cleaning task it shows Fleet [tinyRobot] and Fleet [deliveryRobot] is configured to not accept task [Clean0].

**Screenshots**
![rmf_cleaning_task01](https://user-images.githubusercontent.com/31615486/110196072-13ded000-7e68-11eb-813a-f7b927d80042.png)

**Additional context**
- I looked into the adapter.launch.xml for both robots and noticed  ```<arg name="perform_cleaning" value="false"/> ```,
changed those but still same error.
- Also the locations of the zones_1,2,3.. are not clear inside both worlds....I assumed its defined inside building.yaml file or inside nav_graphs but its not. :(

**Comment by Yadunund** [comment]
Hi @KamalanathanN ,

Thanks for raising this issue. We are currently in the process of updating the demo worlds to showcase cleaning tasks. Will post an update here when this is ready (hopefully within this week or next) along with an explanation.

**Comment by Yadunund** [comment]
Hi @KamalanathanN ,

Sorry for the delay in the update.

First and foremost, we are in the process of migrating all RMF repositories into a dedicated `open-rmf` [organization](https://github.com/open-rmf) to foster greater collaboration with the open source community.

We recently merged a [PR](https://github.com/open-rmf/rmf_demos/pull/8) in `open-rmf/rmf_demos` to introduce cleaning robots into the `airport_terminal` world where they can be instructed to clean floor area (zones). You can follow the instructions [here](https://github.com/open-rmf/rmf#rmf) to install the packages from `open-rmf`.

For more information on how the cleaning task are configured, take a look at the documentation in our online book [here](https://osrf.github.io/ros2multirobotbook/task_types.html#clean-task). Feel free to open issues/discussions in `open-rmf` for additional questions you may have.
