### ISSUE TITLE
RMF Panel report an error

### ISSUE THREAD

**Issue by desstiony** [osrf/rmf_demos#219]
When execute 'ros2 launch demos office.launch.xml'  ，I open http://localhost:5000/, the console reports an error
`app.bundle.js:2 GET http://localhost:8080/socket.io/?EIO=4&transport=polling&t=NXOZApY net::ERR_CONNECTION_REFUSED`
There is no robot summary information in the Robots & Tasks Summaries column。
![image](https://user-images.githubusercontent.com/26624959/111948197-bf02b100-8b19-11eb-8261-6ebdf215bf27.png)

**Comment by tanyouliang95** [comment]
This error seems to be related to `socketio`. Do ensure the local version of `flask-socketio` is (5.x). Meanwhile, you can also try click on the refresh and submit button (which uses REST endpoints) to check if the API server is running successfully.

One heads up is that we are in the process of migrating all rmf related development to [open-rmf](https://github.com/open-rmf/rmf_demos).

**Comment by tanyouliang95** [comment]
In this case, do run some sanity check to check if the `api_server` is failing. (also check the error log, node name is `dispatcher_client`). You can also run the relevant nodes individually via CLI: 
```bash
ros2 run rmf_demos_panel api_server
ros2 run rmf_task_ros2 rmf_task_dispatcher 
curl localhost:8080/robot_list  # check if endpoint is valid
```
