### ISSUE TITLE
Incompatible Gazebo Version

### ISSUE THREAD

**Issue by cnboonhan94** [osrf/rmf_demos#29]
It seems that the command `curl -sSL http://get.gazebosim.org | sh` might now install gazebo 11, while the version compatible with ros2 Eloquent is Gazebo 9, which leads to some installation errors.

Also the README might have some sequence errors right now, in particular the command `rosdep install --from-paths src --ignore-src --rosdistro eloquent` which appears before the creation of the `rmf_demo_ws` folder.

**Comment by aaronchongth** [comment]
the most recent merge should resolve this, https://github.com/osrf/rmf_demos/pull/27, especially on the documented steps.

If there are issues regarding `gazebo`, you can try removing the local installation, following the steps right at the bottom.

**Comment by cnboonhan94** [comment]
gotcha! thanks :dancing_men:
