### ISSUE TITLE
Issue in building rmf_demo_ws

### ISSUE THREAD

**Issue by prashantking** [osrf/rmf_demos#40]
I faced two errors while buidling the rmf_demo_ws with colcon build
1. /usr/include/ignition/msgs1/ignition/msgs/color.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
2. /usr/include/ignition/msgs1/ignition/msgs/world_modify.pb.h:274:93: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’
   return world_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

what needs to be done to solve it ? For detailed error info i am attaching logs.
[log.txt](https://github.com/osrf/rmf_demos/files/4354120/log.txt)

**Comment by aaronchongth** [comment]
This is probably due to an already existing installation of `protobuf` and its compiler, it looks like this might be a similar issue to this, https://answers.gazebosim.org//question/20101/protobuf-version-error-on-ubuntu-1804-and-gazebo9/

Could you provide some information about your system installation of `protobuf`?

```
dpkg -l | grep gazebo9
dpkg -l | grep protobuf
```

**Comment by prashantking** [comment]
attaching two log files with the outputs of above commands
[gazebo9_info.txt](https://github.com/osrf/rmf_demos/files/4355306/gazebo9_info.txt)
[protobuf_info.txt](https://github.com/osrf/rmf_demos/files/4355307/protobuf_info.txt)

**Comment by aaronchongth** [comment]
that looks alright to me. did your system already have an installation of `gazebo9`? or was it installed using the `rosdep` step mentioned in the documentation?

**Comment by prashantking** [comment]
I have a default gazebo installation from
```
sudo apt-get install ros-melodic-desktop-full
```
other than this i tried google cartographer which shows protobuf from source as 3.4.0.
```
$ export PATH=/usr/local/bin:$PATH
$ protoc --version
libprotoc 3.4.0
```
can this create any issue ?

**Comment by aaronchongth** [comment]
looks like you found the problem, it is also referenced in this [issue](https://bitbucket.org/osrf/gazebo/issues/2496/protobuf-error-on-ubuntu-1804) in the past too.

looks like this might be what you need, https://stackoverflow.com/questions/35896335/how-can-i-uninstall-protobuf-3-0-0

**Comment by prashantking** [comment]
rmf_demo needs 3.4.0 version or 3.0.0 version of protoc. ?
since cartographer needs 3.4.0 and default is 3.0.0 which one i should remove ?

**Comment by Yadunund** [comment]
This is an issue that has come up before #21. Gazebo9 requires protobuf `3.0.0` while cartographer installs `3.4.0`. Could you try removing `3.4.0` and confirm if that resolves the issue?

**Comment by cnboonhan94** [comment]
Hi, just sneaking in this link which might help. 

it is for protobuf 3.0.0 but it hopefully works for *removing protobuf 3.4.0*, which is what we want

https://stackoverflow.com/questions/35896335/how-can-i-uninstall-protobuf-3-0-0

We should *change* the instructions in that thread to 3.4.0.

**Comment by prashantking** [comment]
hi, its working now i tried few of the approaches and it worked with this:
go to build directory of protobuf 3.4.0
and then run this command
```
$ cd build
$ sudo cat install_manifest.txt | sudo xargs rm
```
and after this when you compile rmf_demo it works fine. 
although i doubt that cartographer is going to work after this but that can be solved by building protbuf3.4.0 locally in a workspace.
