### ISSUE TITLE
Error Launching office.launch.xml

### ISSUE THREAD

**Issue by KaeYan** [osrf/rmf_demos#55]
OS: Ubuntu 18.04
ROS version: ROS 2 eloquent

I was trying to build and run the rmf_demos, i am able to colcon build with warnings. However, when I tried to launch the office.launch.xml, I encounter the error below:

[INFO] [launch]: All log files can be found below /home/kaeyan/.ros/log/2020-04-02-10-17-01-202640-kaeyan1804-22216
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): The launch file may have a syntax error, or its format is unknown

**Comment by aaronchongth** [comment]
This is probably the same as https://github.com/osrf/rmf_demos/issues/49

A patch is due soon
