### ISSUE TITLE
Delivery on Demos Panel (rviz) only works once

### ISSUE THREAD

**Issue by aaronchongth** [osrf/rmf_demos#61]
* on `office.launch.xml`
* changing the delivery ID  and clicking it again doesn't start a second delivery

**Comment by Yadunund** [comment]
This was [fixed](https://github.com/osrf/rmf_core/pull/88) in the `full_control` fleet adapter by @cnboonhan94 

Did you build with the `master` branch of `rmf_core`?

**Comment by aaronchongth** [comment]
nah, I'm on `develop`, is that the reason?

**Comment by aaronchongth** [comment]
gotcha, this has been fixed before, will just close this issue
