### ISSUE TITLE
Would rosdep require additional dependencies?

### ISSUE THREAD

**Issue by cnboonhan94** [osrf/rmf_demos#64]
Not sure if i am missing something obvious: If I purely install ROS2 and Gazebo, would it be necessary to install any additional dependencies in order for the `rosdep` step to work properly?

**Comment by Yadunund** [comment]
Assuming you have never run `rosdep` before you will need to run the below once
```
sudo rosdep init
rosdep update
```

Does this answer what you had in mind?

**Comment by cnboonhan94** [comment]
i'm not sure if `rosdep` is installed by default if we only install ROS2? I did a clean install recently, installing only `ROS2` and the dependencies specified in the tutorial, but i did not have `rosdep`. should this be expected?

**Comment by aaronchongth** [comment]
Hmm, if you follow the binary installation steps of ROS2, it does mention installing `rosdep`, https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Install-Binary/#installing-and-initializing-rosdep

**Comment by cnboonhan94** [comment]
I knew i missed out something. T.T so sorry to waste your time. Thanks!
