### ISSUE TITLE
rqt unable to view nodes graph

### ISSUE THREAD

**Issue by KaeYan** [osrf/rmf_demos#66]
Hi, after a clean installation, I was able to run the office.launch.xml. However, I cannot seem to view the nodes graph. Can I have a screenshot of how the full nodes graph looks like? Thanks.

$ source ~/rmf_demos_ws/install/setup.bash
$ rqt

![image](https://user-images.githubusercontent.com/26451899/78618579-8f797b00-78ad-11ea-9d25-b1fdb61d997e.png)

**Comment by aaronchongth** [comment]
```
source ~/rmf_demos_ws/install/setup.bash
ros2 run rqt_gui rqt_gui
```
After `rqt_gui` launches, Plugins->Introspection->NodeGraph

![image](https://user-images.githubusercontent.com/5383623/78635433-cadd6f00-78d8-11ea-9339-8573145b1297.png)

**Comment by KaeYan** [comment]
Hi Aaron, I followed the instructions, however still cannot generate the node graph. 

Can you save your node graph as an image instead, at the top right side of the rqt_gui, and attach to me here? 

I would like to know more about the nodes and topics relationship. Thanks!

**Comment by aaronchongth** [comment]
Hello @KaeYan, here is a snapshot of the graph,

![rosgraph](https://user-images.githubusercontent.com/5383623/79563494-81aecb80-80df-11ea-8075-35e90db480b3.jpg)
