### ISSUE TITLE
Relating parameters in adapter and fleet SDF

### ISSUE THREAD

**Issue by cnboonhan94** [osrf/rmf_demos#67]
How might we relate the parameters in the model.sdf, and the model adapter file? Looking at the magni [model.sdf](https://github.com/osrf/rmf_demos/blob/master/rmf_demo_assets/models/Magni/model.sdf), and [magni_adapter.launch.xml](https://github.com/osrf/rmf_demos/blob/master/demos/launch/include/adapters/magni_adapter.launch.xml), it seems there is a difference in values for the same parameter? For example,
```
magni_adapter.launch.xml
  <arg name= "angular_velocity " value="2.2"/>

model.sdf
<nominal_turn_speed>0.6</nominal_turn_speed>
```

**Comment by Yadunund** [comment]
The discrepancy was identified previously and the values are nearly identical in the `fix/airport_scenarios` branch. However, we do notice a delay with the kinematics of the `slotcar` plugin for the MIR model which occasionally leaves the robot lagging behind the trajectory submitted by its fleet_adapter. We're in the process of investigating this.

**Comment by cnboonhan94** [comment]
i see! thank you. I'll keep this issue open for now? to give context for people who use rmf_core. but feel free to close this whenever you see fit.

**Comment by Yadunund** [comment]
Yes let's keep it open until the changes are merged.

**Comment by aaronchongth** [comment]
I think this was just merged this afternoon via https://github.com/osrf/rmf_demos/pull/68, thanks for catching this!
