### ISSUE TITLE
Door not opening

### ISSUE THREAD

**Issue by iReivax1** [osrf/rmf_demos#71]
Hi,

In the office demo, there are times that the door(to go into hardware_2) will not open when the magni robot is outside. There are no errors shown on the terminal for this error.

**Comment by Yadunund** [comment]
Hi,

Could you clarify a couple of points
1) What commands did you issue to rmf (for all robots included)? Did this happen during a `Delivery` request?
2) What was the other robot doing? Any chance it was behind/in-front of the same door?
3) Can you see the planned trajectory of the robot (visualized as green line marker in RViz) from its current position outside the door to `hardware_2`? Similarly can you see the trajectory for the other robot?
4) Did you see any other error in the main terminal along what is described below? 

```
[rmf_traffic_schedule-1] [ERROR] [rmf_traffic_schedule_node]: Requested replacement for ID that does not exist in this Database: ..... still be invalid if they have been culled or erased.
```

Also,
In a separate terminal can you run `ros2 topic echo /door_requests 
` and share the output of that terminal when you see this happening?

**Comment by Yadunund** [comment]
Closing this ticket due to inactivity. @iReivax1 feel free to reopen if the issue still persists.
