### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmf_demos#73]
Address questions pertaining to running demos on physical hardware such as this one
https://answers.ros.org/question/351523/integrating-rmf-and-navigation-stack/
and other integration related questions.

**Comment by SteveMacenski** [comment]
+1 from on the nav stack side, especially as we're in the middle of design discussions to create much of this same capability ourselves...

**Comment by Yadunund** [comment]
Hi @SteveMacenski ,

We finally have a living documentation of RMF that will be regularly updated over time. You can check it out here https://osrf.github.io/ros2multirobotbook/
