### ISSUE TITLE
Simulation models incorrect rotation

### ISSUE THREAD

**Issue by rcywongaa** [osrf/rmf_demos#99]
![image](https://user-images.githubusercontent.com/7285669/86731454-21865080-c062-11ea-8d48-ef78675565d2.png)

When I run the simulation, the various furniture have incorrect rotation leading to collisions when the robot follows the nav graph.

**Comment by Yadunund** [comment]
Hi @rcywongaa 

Does your `traffic_editor` and `rmf_demos` repository contain these fixes? 
https://github.com/osrf/traffic_editor/pull/159
https://github.com/osrf/rmf_demos/pull/90

**Comment by rcywongaa** [comment]
Thanks, that fixed it!
